subscribers:

  camera_reading:
    topic: /long/left/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  obstacle_boxes:
    topic: /cubicle_detection/long_obs
    queue_size: 1
    frame_id: obstacle

  object_detector:
    topic: /cubicle_detection/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /cubicle_detection/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /cubicle_detection/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 3
  enable_console_output: true
